### ISSUE TITLE
Add Screenshots to the Readme.md file

### ISSUE THREAD

**Issue by vinaygaba** [txusballesteros/bubbles-for-android#1]
Hi,
It would really help if you could attach some screenshots to the readme file. A lot of times people might not understand what the library is about or what the end result would be and just skip the page. Screenshots would really help making users understand what the library does :)

**Comment by vinaygaba** [comment]
I see that you have added a gif image. Feel free to close this issue :)

**Comment by txusballesteros** [comment]
@vinaygaba Thx for your comment. 
Regards.
