### ISSUE TITLE
[Question] Open activity/fragment on bubble click?

### ISSUE THREAD

**Issue by PsyGik** [txusballesteros/bubbles-for-android#14]
How can i show a floating Activity/Fragment when I click on the bubble? I could not find anything in the sample app. 

Thanks.

**Comment by txusballesteros** [comment]
@PsyGik You cannot show a floating activity but you can open a normal activity.

**Comment by PsyGik** [comment]
Hey, forgot to tell, I did implement a floating activity. Well, technically not an activity but a floating view service and extended a class that has all the methods which I wanted for the floating activity.

**Comment by fukemy** [comment]
hi @PsyGik , can u provide some example, I really need your solution, thanks so much

**Comment by PsyGik** [comment]
> hi @PsyGik , can u provide some example, I really need your solution, thanks so much

Hello @fukemy , this is a 7 year old thread and I do not have access to the source code anymore. Apologies for not being helpful 🙏🏽

**Comment by fukemy** [comment]
thanks bro, I didnt see the times :D
