### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by Swisyn** [txusballesteros/bubbles-for-android#4]
First of all thanks for sharing this great library! 

Let's say, we have an ui which interacts with the user and then user switches to another app but we want that our app must became a bubble and user can use it while in another app just like the messenger app. From the bubble user can generate data or fetch something to views from a web service or something. The question is how can we use bubble layout's views inside the bubble, how can i determine if the user clicks a button inside the bubble? I couldn't see any example in app about this. It generates the bubble that's great but for what purpose?

**Comment by txusballesteros** [comment]
@Swisyn, you can manage the same way that if you use a normal view. When you inflate your Bubble, you can find your inner views and set the listeners.
